### ISSUE TITLE
Gradle runner init script hides some env variables 

### ISSUE THREAD

**Issue by RainM** [JetBrains/teamcity-gradle#10]
Gradle runner script hides GRADLE_OPTS variable in case of it's passed somewhere outside. My case: I pass this variable via docker '-e' argument and don't get actual value at gradle run.

Proposed fix: concatenate previous env var's value and items you want to add.

https://github.com/JetBrains/teamcity-gradle/blob/036ea9306af23d3500c21b6253fd16d28e871df4/gradle-runner-agent/src/main/java/jetbrains/buildServer/gradle/agent/GradleRunnerService.java#L106

**Comment by dmitry-treskunov** [comment]
Hi, you may try to add GRADLE_OPTS as an environment variable to the build configuration on the Parameters tab, it should work.
