### ISSUE TITLE
Gradle.useLogger has been deprecated in Gradle 8.11

### ISSUE THREAD

**Issue by osipxd** [JetBrains/teamcity-gradle#14]
Method Gradle.useLogger has been [deprecated](https://docs.gradle.org/8.11/userguide/upgrading_version_8.html#deprecated_use_logger) and scheduled to be removed in Gradle 9.0.

https://github.com/JetBrains/teamcity-gradle/blob/85903336928bb1a564152e5307f7ede8e30a3dad/gradle-runner-agent/src/main/scripts/init.gradle#L1278

**Comment by kim-vitaliy** [comment]
Hi @osipxd!

In the new launch method using the Tooling API, `Gradle.useLogger` is not utilized. As you can see, this method is absent in the corresponding [init script](https://github.com/JetBrains/teamcity-gradle/blob/85903336928bb1a564152e5307f7ede8e30a3dad/gradle-runner-agent/src/main/scripts/init_since_8.gradle).

Currently, to use the new launch method, you need to:
- Have Gradle version 8 or higher;
- Use the `configuration-cache` in your project or set the following config parameter: `teamcity.internal.gradle.runner.launch.mode=auto`.

Please try this for your project.
