### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke method toBoolean() on null object

### ISSUE THREAD

**Issue by AltmanMMMMM** [JetBrains/teamcity-gradle#3]
java.lang.NullPointerException: Cannot invoke method toBoolean() on null object
09:48:39
  FAILURE: Build failed with an exception.
09:48:39
  
09:48:39
  * Where:
09:48:39
  Initialization script '/opt/buildagent/plugins/gradle-runner/scripts/init.gradle' line: 776
09:48:39
  
09:48:39
  * What went wrong:
09:48:39
  Cannot invoke method toBoolean() on null object
09:48:39
  
09:48:39
  * Try:
09:48:39
  Run with --info or --debug option to get more log output. Run with --scan to get full insights.
09:48:39
  
09:48:39
  * Exception is:
09:48:39
  java.lang.NullPointerException: Cannot invoke method toBoolean() on null object
09:48:39
    at TeamcityRerunTestsListener.projectsEvaluated(/opt/buildagent/plugins/gradle-runner/scripts/init.gradle:776)
09:48:39
    at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingInvocationHandler$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:236)

**Comment by AltmanMMMMM** [comment]
this is the pr:    https://github.com/JetBrains/teamcity-gradle/pull/5

**Comment by madlexa** [comment]
The bug is not reproduced.
