### ISSUE TITLE
 Could not find matching constructor for: java.io.File(String, File)

### ISSUE THREAD

**Issue by SeanBurnsUK** [JetBrains/teamcity-gradle#6]
There is a bug in team city init.gradle script.

When teamcity detects that there is a large stack trace it uses _attachBigFailTestMessage_ and attempts to create a file using the private constructor of java.io.File and exits with an error.

`private File(String child, File parent)`

It should use the public constructor

`public File(File parent, String child)`

[https://github.com/JetBrains/teamcity-gradle/blob/2152d715a39f0f29eb27a2b68a15db24bf07574a/gradle-runner-agent/src/main/scripts/init.gradle#L759](https://github.com/JetBrains/teamcity-gradle/blob/2152d715a39f0f29eb27a2b68a15db24bf07574a/gradle-runner-agent/src/main/scripts/init.gradle#L759)

**Comment by madlexa** [comment]
@SeanBurnsUK Thanks for the help.
